async function fetchData() {
  const apiUrl = "https://ipapi.co/json";
  const res = await fetch(apiUrl);
  const data = await res.json();
  console.log(data);
  localStorage.setItem("ip", data.ip);
  localStorage.setItem("network", data.network);
  localStorage.setItem("version", data.version);
  localStorage.setItem("city", data.city);
  localStorage.setItem("region", data.region);
  localStorage.setItem("region_code", data.region_code);
  localStorage.setItem("country", data.country);
  localStorage.setItem("country_name", data.country_name);
  localStorage.setItem("country_code", data.country_code);
  localStorage.setItem("country_code_iso3", data.country_code_iso3);
  localStorage.setItem("country_capital", data.country_capital);
  localStorage.setItem("country_tld", data.country_tld);
  localStorage.setItem("continent_code", data.continent_code);
  localStorage.setItem("in_eu", data.in_eu);
  localStorage.setItem("postal", data.postal);
  localStorage.setItem("latitude", data.latitude);
  localStorage.setItem("longitude", data.longitude);
  localStorage.setItem("timezone", data.timezone);
  localStorage.setItem("utc_offset", data.utc_offset);
  localStorage.setItem("country_calling_code", data.network);
  localStorage.setItem("currency", data.currency);
  localStorage.setItem("currency_name", data.currency_name);
  localStorage.setItem("languages", data.languages);
  localStorage.setItem("country_area", data.country_area);
  localStorage.setItem("country_population", data.country_population);
  localStorage.setItem("asn", data.asn);
  localStorage.setItem("org", data.org);
}
const fetchBtn = document.getElementById("fetchBtn");
fetchBtn.addEventListener("click", fetchData);
const ipvar = document.getElementById("ip");
ipvar.innerHTML = localStorage.getItem("ip");
const net = document.getElementById("network");
net.innerHTML = localStorage.getItem("network");
const ver = document.getElementById("version");
ver.innerHTML = localStorage.getItem("version");
const cityvar = document.getElementById("city");
cityvar.innerHTML = localStorage.getItem("city");
const regionvar = document.getElementById("region");
regionvar.innerHTML = localStorage.getItem("region");
const region_codevar = document.getElementById("region_code");
region_codevar.innerHTML = localStorage.getItem("region_code");
const countryvar = document.getElementById("country");
countryvar.innerHTML = localStorage.getItem("country");
const country_namevar = document.getElementById("country_name");
country_namevar.innerHTML = localStorage.getItem("country_name");
const country_codevar = document.getElementById("country_code");
country_codevar.innerHTML = localStorage.getItem("country_code");
const country_code_iso3var = document.getElementById("country_code_iso3");
country_code_iso3var.innerHTML = localStorage.getItem("country_code_iso3");
const country_capitalvar = document.getElementById("country_capital");
country_capitalvar.innerHTML = localStorage.getItem("country_capital");
const country_tldvar = document.getElementById("country_tld");
country_tldvar.innerHTML = localStorage.getItem("country_tld");
const continent_codevar = document.getElementById("continent_code");
continent_codevar.innerHTML = localStorage.getItem("continent_code");
const in_euvar = document.getElementById("in_eu");
in_euvar.innerHTML = localStorage.getItem("in_eu");
const postalvar = document.getElementById("postal");
postalvar.innerHTML = localStorage.getItem("postal");
const latitudevar = document.getElementById("latitude");
latitudevar.innerHTML = localStorage.getItem("latitude");
const longitudevar = document.getElementById("longitude");
longitudevar.innerHTML = localStorage.getItem("longitude");
const timezonevar = document.getElementById("timezone");
timezonevar.innerHTML = localStorage.getItem("timezone");
const utc_offsetvar = document.getElementById("utc_offset");
utc_offsetvar.innerHTML = localStorage.getItem("utc_offset");
const country_calling_codevar = document.getElementById("country_calling_code");
country_calling_codevar.innerHTML = localStorage.getItem(
  "country_calling_code"
);
const currencyvar = document.getElementById("currency");
currencyvar.innerHTML = localStorage.getItem("currency");
const currency_namevar = document.getElementById("currency_name");
currency_namevar.innerHTML = localStorage.getItem("currency_name");
const languagesvar = document.getElementById("languages");
languagesvar.innerHTML = localStorage.getItem("languages");
const country_areavar = document.getElementById("country_area");
country_areavar.innerHTML = localStorage.getItem("country_area");
const country_populationvar = document.getElementById("country_population");
country_populationvar.innerHTML = localStorage.getItem("country_population");
const asnvar = document.getElementById("asn");
asnvar.innerHTML = localStorage.getItem("asn");
const orgvar = document.getElementById("org");
orgvar.innerHTML = localStorage.getItem("org");
